version: 1
formatters:
  simpleFormatter:
    format: '%(asctime)s %(levelname)7s %(filename)14s:%(lineno)3d| %(message)s'
    datefmt: '%Y%m%d %H%M%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simpleFormatter
    stream: ext://sys.stdout
  filedebug:
    class: logging.handlers.WatchedFileHandler
    level: DEBUG
    formatter: simpleFormatter
    filename: ../logs/avmonitor.log
  fileinfo:
    class: logging.FileHandler
    level: INFO
    formatter: simpleFormatter
    filename: ../logs/avmonitor-info.log
  fileerror:
    class: logging.FileHandler
    level: WARN
    formatter: simpleFormatter
    filename: ../logs/avmonitor-error.log
loggers:
  avmonitor:
    level: DEBUG
    handlers: [console, filedebug, fileinfo, fileerror]
    propagate: no
root:
  level: DEBUG
  handlers: [console, fileinfo, filedebug, fileerror]